name = "talix-api"
main = "src/index.ts"
compatibility_date = "2023-01-23"

account_id = "8f677fd195b2d505617e10661bc8e59d"

workers_dev = true

[[r2_buckets]]
binding = 'DOCUMENTS_BUCKET' # <~ valid JavaScript variable name
bucket_name = 'talix-documents'
preview_bucket_name = 'talix-documents-preview'


[durable_objects]
bindings = [
  { name = "DOCUMENT_ENTITY", class_name = "DocumentEntity" } # Binding to our DurableObjectExample class
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["DocumentEntity"]

[[queues.producers]]
  queue = "event-queue"
  binding = "EVENT_QUEUE"

[[queues.consumers]]
  queue = "event-queue"
  max_batch_size = 1
  max_batch_timeout = 1