name = "talix-api"
main = "src/index.ts"
compatibility_date = "2023-01-23"

account_id = "8f677fd195b2d505617e10661bc8e59d"

workers_dev = true


kv_namespaces = [
  { binding = "SESSION_STORAGE", id = "f8831fadebe04f5f985ddf91236cf5f2", preview_id = "f8831fadebe04f5f985ddf91236cf5f2" }
]


[[r2_buckets]]
binding = 'DOCUMENTS_BUCKET' # <~ valid JavaScript variable name
bucket_name = 'talix-documents'
preview_bucket_name = 'talix-documents-preview'


[durable_objects]
bindings = [
  { name = "DURABLE_ENTITY", class_name = "DurableEntity" } # Binding to our DurableObjectExample class
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["DurableEntity"]

[[queues.producers]]
  queue = "talix-event-queue"
  binding = "EVENT_QUEUE"

[[queues.consumers]]
  queue = "talix-event-queue"
  max_batch_size = 1
  max_batch_timeout = 1

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "default"
database_id = "9693008c-5582-4966-a69c-02e5d5429658"
#preview_database_id = "a487f610-4a5f-4562-9d46-7b6c291b5312"
