name: CI

on:
    push:
    pull_request:

jobs:
    CI:
        runs-on: ubuntu-latest
        env:
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
            TURBO_REMOTE_ONLY: true
            CF_R2_ACCESS_KEY_ID: ${{ secrets.CF_R2_ACCESS_KEY_ID }}
            CF_R2_SECRET_ACCESS_KEY: ${{ secrets.CF_R2_SECRET_ACCESS_KEY }}
            CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2
              with:
                  version: 6.32.9
            - uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  cache: 'pnpm'
            - run: pnpm install --frozen-lockfile

            - run: pnpm turbo run lint test type-check build --output-logs full

    # deploy:
    #     runs-on: ubuntu-latest
    #     if: ${{ github.event_name  == 'push' }}
    #     if: ${{ github.ref == 'refs/heads/main' }}
    #     needs: [CI]
    #     environment:
    #         name: deploy
    #     env:
    #         TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    #         TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    #         TURBO_REMOTE_ONLY: true

    #     steps:
    #         - name: Checkout
    #           uses: actions/checkout@v3

    #         - uses: pnpm/action-setup@v2
    #           with:
    #               version: 6.32.9
    #         - uses: actions/setup-node@v3
    #           with:
    #               node-version: '18'
    #               cache: 'pnpm'
    #         - run: pnpm install --frozen-lockfile

    #         - name: Deploy
    #           run: pnpm run deploy
